<?php

namespace Acme\BlogBundle\Repository;

use Doctrine\ORM\Query;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @var \Doctrine\ORM\QueryBuilder
     */
    protected $query;

    /**
     * Builds query
     *
     * @param array $params parameters for search
     *
     * @return $this
     */
    public function buildQuery($params = array())
    {
        if (!$this->query) {
            $this->query = $this->createQueryBuilder('tbl');
        }

        return $this;
    }

    /**
     * Reset query parameters
     *
     * @return $this
     */
    public function reset()
    {
        $this->query = $this->createQueryBuilder('tbl');

        return $this;
    }

    /**
     * Get single item
     *
     * @return mixed
     */
    public function getSingle()
    {
        return $this->query
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function getResult()
    {
//        var_dump($this->query
//                     ->getQuery()
//                     ->getSQL());die;

        return $this->query
            ->getQuery()
            ->getResult(/*Query::HYDRATE_ARRAY*/);
    }

    /**
     * Returns count of items
     *
     * @return int count of all members
     */
    public function getCount()
    {
        $query = clone $this->query;
        $result = $query
            ->select(array('COUNT(tbl.id)'))
            ->setFirstResult(null)
            ->setMaxResults(null)
            ->getQuery()
            ->getOneOrNullResult();

        return $result?current($result):0;
    }
}
