acme_blog_Category:
    type: rest
    prefix: /v1
    resource: Acme\BlogBundle\Controller\CategoryController
    name_prefix:  api_1_ # naming collision

acme_blog_Page:
    type: rest
#    prefix: /v1
    resource: Acme\BlogBundle\Controller\PageController
    name_prefix:  api_1_ # naming collision
    parent:   acme_blog_Category

acme_blog_Token:
    type: annotation
    prefix: /v1
    resource: Acme\BlogBundle\Controller\TokenController
    name_prefix:  api_1_ # naming collision