services:
  acme_blog.page.handler:
    class: Acme\BlogBundle\Handler\PageHandler
    arguments:
      - "@doctrine.orm.entity_manager"
      - Acme\BlogBundle\Entity\Page
      - "@form.factory"
  acme_blog.page.password_encoder:
    class: Acme\BlogBundle\Security\PasswordEncoder

#    acme_blog.example:
#        class: Acme\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
