Acme\BlogBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
#            groups: [students, admins]
        title:
            expose: true
#            groups: [students, admins]
        body:
            expose: true
#            groups: [students, admins]
        postedBy:
            expose: true
                type:   Acme\BlogBundle\Entity\User
                xml_list:
                    inline: true
                    entry_name: division
#            groups: [admins]